# Generated by Django 5.2.8 on 2025-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timestamp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="action",
            field=models.CharField(
                choices=[("pee", "Pee"), ("pill", "Pill")], max_length=10
            ),
        ),
    ]
