# Generated by Django 5.2.8 on 2025-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timestamp", "0002_alter_logentry_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Note"),
        ),
    ]
