# Generated by Django 5.2.8 on 2025-12-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timestamp", "0004_note_remove_logentry_note_logentry_short_note_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="volume",
            field=models.IntegerField(
                blank=True, help_text="Volume for pee (optional)", null=True
            ),
        ),
    ]
