# Generated by Django 5.2.8 on 2025-12-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timestamp", "0005_logentry_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Body weight in kg",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("pee", "Pee"),
                    ("poo", "Poo"),
                    ("pill", "Pill"),
                    ("weight", "Weight"),
                ],
                max_length=10,
            ),
        ),
    ]
